version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "docker"
      include: "scope"

  # Zig dependencies (if we add build.zig.zon in the future)
  # Note: Dependabot doesn't natively support Zig yet, but this is future-proofing
  # - package-ecosystem: "zig"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #     day: "sunday"
  #   open-pull-requests-limit: 5
  #   labels:
  #     - "dependencies"
  #     - "zig"