name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of lsp-mcp-server are you using?
      placeholder: "v0.1.0 or commit hash"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
        - FreeBSD
        - Other (please specify in description)
    validations:
      required: true

  - type: input
    id: installation
    attributes:
      label: Installation Method
      description: How did you install lsp-mcp-server?
      placeholder: "Homebrew, Docker, build from source, etc."
    validations:
      required: true

  - type: input
    id: language-server
    attributes:
      label: Language Server
      description: Which language server were you using when the bug occurred?
      placeholder: "zls, rust-analyzer, gopls, typescript-language-server, etc."
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: "A clear and concise description of what the bug is."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Please provide step-by-step instructions to reproduce the issue
      placeholder: |
        1. Start lsp-mcp-server with '...'
        2. Send request '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Please share your lsp-mcp-server configuration if relevant
      render: json
    validations:
      required: false

  - type: input
    id: ai-assistant
    attributes:
      label: AI Assistant
      description: Which AI assistant were you using (if applicable)?
      placeholder: "Claude Code, Claude Desktop, Gemini CLI, etc."
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true